### ISSUE TITLE
Leitura de matriz

### ISSUE THREAD

**Issue by nobnet** [erickweil/portugolweb#2]
Olá, tudo bem? Gostei da sua implementação, mas encontrei um problema quando tento realizar leitura de matrizes.

**Comment by erickweil** [comment]
Verifique se está funcionando. acabei de testar está tudo ok agora.

**Comment by nobnet** [comment]
> Verifique se está funcionando. acabei de testar está tudo ok agora.

Sim. Muito obrigado
