### ISSUE TITLE
Inicialização de vetor e matriz com tamanho implícito

### ISSUE THREAD

**Issue by nobnet** [erickweil/portugolweb#4]
Boa tarde. Vi que a inicialização de vetor e matriz com tamanho implícito não está funcionando, conforme a sintaxe abaixo:
	funcao inicio()
	{
		real v[] = {1.1, 2.4}
		real m[][2] = {{1.1,1.2},{2.3,1.3}}
	}
Poderia resolvê-lo?

**Comment by erickweil** [comment]
Este Bug apareceu devido a correção anterior que permite retorno de vetores e matrizes. Voltou a funcionar como deveria.

Obs: esta linha, `real m[][2] = {{1.1,1.2},{2.3,1.3}}` deveria ser `real m[][] = {{1.1,1.2},{2.3,1.3}}`, ou todos os tamanhos da matriz são implícitos, ou se declara todos os tamanhos da matriz, não pode declarar apenas parte dos tamanhos da matriz.
