### ISSUE TITLE
Falha em caracteres acentuados

### ISSUE THREAD

**Issue by nobnet** [erickweil/portugolweb#5]
Há algum problema na codificação dos caracteres na web.

**Comment by erickweil** [comment]
Favor, descreva melhor o problema, nos testes que fiz os arquivos foram salvos como UTF-8 e não houve problemas nem mesmo ao abri-los no Portugol Studio ou outro editor.

Inclusive foi possível abrir arquivos do Portugol Studio sem problemas nos acentos ou algo do tipo.

Dê um exemplo de quando esse problema ocorre ou anexe um arquivo problemático.

**Comment by nobnet** [comment]
Falha minha. O problema é que o Windows está salvando como ANSI e quando abre, caracteres estranhos aparecem. Acho que essa issue pode ser fechada.
