### ISSUE TITLE
Ferramenta colaborativa com TogetherJS

### ISSUE THREAD

**Issue by nobnet** [erickweil/portugolweb#8]
Olá. Gostaria de requisitar a adição de uma característica na versão web que será bem interessante.
É a possibilidade de colaboração em tempo real com o uso da biblioteca TogetherJS.
Fiz um teste com ela localmente e ela funcionou perfeitamente. Para isso, as seguintes linhas de código seriam adicionadas:

```
<script>
	TogetherJSConfig_hubBase = "https://togetherjs-hub.glitch.me/"
</script>
<script src="https://togetherjs.com/togetherjs-min.js"></script>
```

 
Juntamente com um botão na barra de botões (executar, exemplos e etc)
`<button onclick="TogetherJS(this); return false;">Start TogetherJS</button>`

Mais detalhes em: https://togetherjs.com/docs/

Muito obrigado.

**Comment by erickweil** [comment]
Adicionei um botão na tela de Exemplos, clicando nele o TogheterJS é ativado.

O botão não é visível quando aberto em dispositivos móveis.

**Comment by erickweil** [comment]
Está dando problemas, estarei vendo porque não funciona.

**Comment by nobnet** [comment]
Estava testando e realmente parece não funcionar. Só lembrando que é uma biblioteca que está sem manutenção pela Mozilla e parece que apenas jsfiddle está fazendo isso, mas não o faz com regularidade.
Mesmo assim, você está fazendo um excelente trabalho em testá-la.
Muito obrigado.
