### ISSUE TITLE
Erro com a biblioteca Util

### ISSUE THREAD

**Issue by moura79** [erickweil/portugolweb#9]
![Screenshot_20210107-151707](https://user-images.githubusercontent.com/72673933/104008010-94929000-5187-11eb-9169-ff2f9f0544c8.png)
Está dando erro quando coloco :

se(t.cadeia_e_inteiro(teclado, 10))
num = t.cadeia_para_inteiro(teclado, 10)
diz que a base tem  que  ser 2,16 ou 10

**Comment by erickweil** [comment]
Corrigido, Agora a biblioteca Tipos deveria funcionar corretamente.

Obs, essas mudanças por enquanto estarão disponíveis apenas no editor web https://erickweil.github.io/portugolweb/
No aplicativo vai ser corrigido apenas na próxima vez que o aplicativo for atualizado.

**Comment by moura79** [comment]
Obrigado

Em sex, 22 de jan de 2021 20:44, Erick Leonardo Weil <
notifications@github.com> escreveu:

**Comment by moura79** [comment]
Funcionou  no portugol web

Em dom, 24 de jan de 2021 07:40, Anderson De Moura <
anndersonnmoura@gmail.com> escreveu:
